### ISSUE TITLE
Feature #1: User-can-record-an-audio-file

### ISSUE THREAD

**Issue by adrienne-yung** [adrienne-yung/final-project#1]
## ⚙️ Feature #1

> ##### What capability will users have when this feature is merged?
User can record an audio file (an audio file is created)

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on "Record Audio File" on the homepage will send user to another view where they can click on the microphone icon and start an audio recording that generates an audio file for them

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature1](https://user-images.githubusercontent.com/90871776/153962772-dc5cdeba-9ab1-4b4b-8156-f0c04893fc4c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to https://app.dbdesigner.net/designer/schema/498489
- [ ] Update `data.sql` to insert information when data is made 

### ☁️ Server

- [ ] Update `server/index.js` to post when the file recording is made 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] (HTML/CSS) Create a homepage containing the image/button "Record an Audio File"
- [ ] (JS)Element "Record an Audio File" opens a view/page that allows users to start their audio recording by clicking a microphone icon
- [ ] (CSS) Create brief instructions to how to record audio file
- [ ]  (JS) Ask user for microphone access permission
- [ ] (JS) Upon clicking the recording button while it is white, starts audio recording
- [ ] (JS) Upon clicking the recording button while it is red, stops recording and then generates an audio file
- [ ] (JS) Audio file is stored in a playlist under instructions 
- [ ] (JS/CSS) A play button should be created for the audio file 
- [ ] (JS) If the play button is clicked, audio file will play. Play button is changed to Pause Button. When recording is over, play button 
will automatically change to Pause Button
- [ ] If Pause Button is clicked before Audio file is finished, audio file will stop playing. Pause Button will become Play Button. Audio File will be reset to 0:00 mins/seconds

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
