### ISSUE TITLE
Feature #3: User-can-change-application-colors

### ISSUE THREAD

**Issue by adrienne-yung** [adrienne-yung/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can change the background color and font color of the web application

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon clicking the settings icon, user will be shown to possible changes they can make the the font color and background color to the application

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature10](https://user-images.githubusercontent.com/90871776/153967200-b3721d52-0808-4e4d-b4ad-77c583003998.png)

![feature10d](https://user-images.githubusercontent.com/90871776/153967320-a4bb8292-6a3c-496d-82eb-140622484991.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Handle all errors 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
