### ISSUE TITLE
Feature #1: User-can-translate-speech-to-text

### ISSUE THREAD

**Issue by adrienne-yung** [adrienne-yung/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Upon clicking on the recording icon, user will see the words they speak translate to text in a textbox in real-time. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on the recording button will activate the textbox to record whatever they say and translate it to text they speak. Once the recording is stopped, text is still shown. Audio file is still created (as applied in the first feature)

## 🖼️ Wireframes
![feature5](https://user-images.githubusercontent.com/90871776/153966034-29966b28-ae03-4bcb-9698-6858af61b2c6.png)
![feature6d](https://user-images.githubusercontent.com/90871776/153970909-be6ae459-dcce-4922-abaa-e06b66ecd551.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to ...

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
