### ISSUE TITLE
Feature #2: User-can-translate-text-to-speech

### ISSUE THREAD

**Issue by adrienne-yung** [adrienne-yung/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can type in a textbox and app will generate an audio file recording of what they've typed

## 📐 Functionality

User can type into a textbox and upon submitting the text, an audio file will be generated that translates their text into speech

## 🖼️ Wireframes

![feature6](https://user-images.githubusercontent.com/90871776/153966247-7dd901a4-f795-488e-ac99-75727188875e.png)

![feature5d](https://user-images.githubusercontent.com/90871776/153971006-f2cdbbc7-cb28-4fbd-97f3-8f8c2c7d4b81.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Handle all errors 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
